const quotes = {
  aurelius: [
    { text: "You have power over your mind, not outside events. Realise this, and you will find strength.", source: "Meditations" },
    { text: "The impediment to action advances action. What stands in the way becomes the way.", source: "Meditations" },
    { text: "Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.", source: "Meditations" },
    { text: "If it is not right, do not do it; if it is not true, do not say it.", source: "Meditations" },
    { text: "Waste no more time arguing about what a good man should be. Be one.", source: "Meditations" },
    { text: "The best revenge is to be unlike him who performed the injury.", source: "Meditations" },
    { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", source: "Meditations" },
    { text: "Do not indulge in dreams of what you have not, but count the blessings actually present.", source: "Meditations" },
    { text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", source: "Meditations" },
    { text: "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.", source: "Meditations" },
    { text: "How much more grievous are the consequences of anger than the causes of it.", source: "Meditations" },
    { text: "He who lives in harmony with himself lives in harmony with the universe.", source: "Meditations" },
    { text: "The soul becomes dyed with the colour of its thoughts.", source: "Meditations" },
    { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", source: "Meditations" },
    { text: "Begin at once to live, and count each separate day as a separate life.", source: "Meditations" },
    { text: "Think of yourself as dead. You have lived your life. Now take what's left and live it properly.", source: "Meditations" },
    { text: "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", source: "Meditations" },
    { text: "Do not act as if you had ten thousand years to live.", source: "Meditations" },
    { text: "A man's worth is no greater than his ambitions.", source: "Meditations" },
    { text: "Loss is nothing else but change, and change is Nature's delight.", source: "Meditations" },
    { text: "Confine yourself to the present.", source: "Meditations" },
    { text: "It is not death that a man should fear, but he should fear never beginning to live.", source: "Meditations" },
    { text: "When you wake up in the morning, tell yourself: the people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous and surly.", source: "Meditations" },
    { text: "Receive without pride, abandon without struggle.", source: "Meditations" },
    { text: "The impediment to action advances action. What stands in the way becomes the way.", source: "Meditations" },
    { text: "Perfection of character is this: to live each day as if it were your last, without frenzy, without apathy, without pretence.", source: "Meditations" },
    { text: "If someone is able to show me that what I think or do is not right, I will happily change.", source: "Meditations" },
    { text: "You could leave life right now. Let that determine what you do and say and think.", source: "Meditations" },
    { text: "Nothing has such power to broaden the mind as the ability to investigate systematically and truly all that comes under thy observation in life.", source: "Meditations" },
    { text: "The happiness of your life depends upon the quality of your thoughts.", source: "Meditations" }
  ],
  dostoevsky: [
    { text: "Pain and suffering are always inevitable for a large intelligence and a deep heart.", source: "Crime and Punishment" },
    { text: "The mystery of human existence lies not in just staying alive, but in finding something to live for.", source: "The Brothers Karamazov" },
    { text: "To live without Hope is to Cease to live.", source: "Letters" },
    { text: "Above all, don't lie to yourself. The man who lies to himself and listens to his own lie comes to a point that he cannot distinguish the truth within him, or around him, and so loses all respect for himself and for others.", source: "The Brothers Karamazov" },
    { text: "There are things which a man is afraid to tell even to himself, and every decent man has a number of such things stored away in his mind.", source: "Notes from Underground" },
    { text: "The soul is healed by being with children.", source: "The Idiot" },
    { text: "It takes something more than intelligence to act intelligently.", source: "Crime and Punishment" },
    { text: "Man only likes to count his troubles; he doesn't calculate his happiness.", source: "Notes from Underground" },
    { text: "Beauty will save the world.", source: "The Idiot" },
    { text: "To go wrong in one's own way is better than to go right in someone else's.", source: "Crime and Punishment" },
    { text: "The darker the night, the brighter the stars. The deeper the grief, the closer is God.", source: "The Brothers Karamazov" },
    { text: "We sometimes encounter people, even perfect strangers, who begin to interest us at first sight.", source: "The Idiot" },
    { text: "Happiness does not lie in happiness, but in the achievement of it.", source: "A Writer's Diary" },
    { text: "Nothing in this world is harder than speaking the truth, nothing easier than flattery.", source: "The Idiot" },
    { text: "A real gentleman, even if he loses everything he owns, must show no emotion. Money must be so far beneath a gentleman that it is hardly worth troubling about.", source: "The Gambler" },
    { text: "The formula 'Two plus two equals five' is not without its attractions.", source: "Notes from Underground" },
    { text: "Right or wrong, it's very pleasant to break something from time to time.", source: "The Idiot" },
    { text: "Much unhappiness has come into the world because of bewilderment and things left unsaid.", source: "The Idiot" },
    { text: "Love in action is a harsh and dreadful thing compared with love in dreams.", source: "The Brothers Karamazov" },
    { text: "The cleverest of all, in my opinion, is the man who calls himself a fool at least once a month.", source: "The Brothers Karamazov" },
    { text: "If you want to be respected by others, the great thing is to respect yourself.", source: "The Insulted and Humiliated" },
    { text: "Man is sometimes extraordinarily, passionately, in love with suffering.", source: "Notes from Underground" },
    { text: "There is only one means of salvation, then take yourself and make yourself responsible for all men's sins.", source: "The Brothers Karamazov" },
    { text: "A fool with a heart and no sense is just as unhappy as a fool with sense and no heart.", source: "The Idiot" },
    { text: "We are all responsible to all for all, it is only that men do not know this.", source: "The Brothers Karamazov" },
    { text: "Compassion is the chief law of human existence.", source: "The Idiot" },
    { text: "What is hell? I maintain that it is the suffering of being unable to love.", source: "The Brothers Karamazov" },
    { text: "Power is given only to those who dare to lower themselves and pick it up.", source: "Crime and Punishment" },
    { text: "To love someone means to see them as God intended them.", source: "The Brothers Karamazov" },
    { text: "The greatest happiness is to know the source of unhappiness.", source: "A Writer's Diary" }
  ]
};

module.exports = quotes;
